INSERT INTO SEZIONE VALUES
(1, 'Funzioni di più variabili', 'Estensione dei risultati ottenuti per le funzioni di una variabile viste in Analisi 1 a funzioni in più variabili, eventualmente vettoriali'),
(2, 'Integrali curvilinei e forme differenziali', 'Trattazione degli integrali di funzioni scalari e vettoriali calcolati lungo curve'),
(3, 'Integrazione di funzioni di più variabili', 'Calcolo di integrali doppi e tripli, rispettivamente di funzioni scalari in due e in tre variabili'),
(4, 'Superfici e integrali di superficie', 'Definizione e calcolo dell area di superfici con parametrizzazione, calcolo di flussi di funzioni vettoriali attraverso superfici'),
(5, 'Equazioni differenziali ordinarie', 'Studio di equazioni aventi come variabile una funzione scalare di cui compaiono derivate di ordine almeno 1 nell equazione'),
(6, 'Funzioni olomorfe e di variabile complessa', 'Introduzione dei concetti fondamentali di analisi complessa');

INSERT INTO ARGOMENTO VALUES
(1, 1, 'Topologia in Rn', 'Definizioni e classificazioni di insiemi in Rn che stanno alla base della definizione di limite.'),
(2, 1, 'Limiti', 'Indicazioni sul comportamento di funzioni in prossimità di un valore eventualmente vettoriale.'),
(3, 2, 'Curve', 'Funzioni da una variabile in piu variabili.'),
(4, 1, 'Funzioni continue', 'Definizione di continuità di una funzione ed estensione di alcuni teoremi sulle funzioni continue visti in analisi 1 a funzioni scalari in più variabili.'),
(5, 1, 'Calcolo differenziale di funzioni scalari in più variabili', 'Esposizione dei concetti di derivabilità e differenziabilità, derivate parziali e gradiente.'),
(6, 1, 'Forme quadratiche', 'Introduzione ed eventuali richiami di risultati relativi al calcolo algebrico e matriciali utili per lo studio del comportamento di una funzione in punti critici.'),
(7, 1, 'Insiemi convessi e funzioni convesse', 'Definizione di convessità o concavità di una funzione scalare in più variabili in un punto del suo dominio.'),
(8, 1, 'Massimi e minimi', 'Studio dei punti di estremo di una funzione nel suo domino.'),
(9, 1, 'Funzioni a valori vettoriali', 'Estensione del concetti di differenziabilità e delle procedure di derivazione per funzioni vettoriali in più variabili.'),
(10, 1, 'Integrali dipendenti da parametri', 'Trattazione dei teoremi di passaggio al limite e di derivazione sotto il segno di integrale.'),
(11, 2,'Curve di livello','Luogo dei punti del dominio di una funzione in cui questa assume un certo valore'),
(12, 2,'Integrali di funzioni vettoriali di una variabile','Estensione del concetto di integrale a funzioni vettoriali di una variabile'),
(13, 2,'Integrali curvilinei','Integrale di una funzione lungo una curva'),
(14, 2,'Forme differenziali','Formalizzazione matematica del concetto di lavoro in Fisica'),
(15, 3,'Integrali doppi su un rettangolo','Definizione dell integrale doppio di una funzione calcolato su un rettangolo'),
(16, 3,'Integrali doppi: caso generale','Definizione dell integrale doppio di una funzione calcolato su un generico sottoinsieme del piano'),
(17, 3,'Integrali tripli','Definizione dell integrale di una funzione su un sottoinsieme dello spazio tridimensionale'),
(18, 3,'Integrali su domini illimitati','Definizione dell integrale di una funzione su un sottoinsieme illimitato dello spazio tridimensionale'),
(19, 4,'Superfici parametriche regolari','Definizione di superfici parametriche come evoluzione delle curve parametriche'),
(20, 4,'Integrali superficiali','Integrali di funzioni scalari e vettoriali calcolati su una superficie parametrica'),
(21, 4,'Teorema della divergenza','Equivalenza tra flusso di una funzione vettoriale attraverso una superficie chiusa e integrale triplo della sua divergenza'),
(22, 4,'Teorema del rotore','Equivalenza tra flusso del rotore di una funzione vettoriale attraverso una superficie e la sua circuitazione lungo il bordo della superficie'),
(23, 5,'Equazioni lineari del primo ordine',null),
(24, 5,'Equazioni del primo ordine a variabili separabili',null),
(25, 5,'Problema di Cauchy',null),
(26, 5,'Sistemi del primo ordine in forma normale',null),
(27, 5,'Sistemi lineari',null),
(28, 5,'Sistemi lineari a coefficienti costanti',null),
(29, 6,'Funzioni di variabile complessa','Introduzione alle funzioni a valori complessi di variabile complessa'),
(30, 6,'Esempi di Funzioni olomorfe','Estensione di alcune delle funzioni principali alla loro versione di variabile complessa'),
(31, 6,'Integrali curvilinei di funzioni complesse','Integrali di funzioni complesse di variabile complessa calcolati lungo una curva nel piano complesso'),
(32, 6,'Derivate di ordine superiore','Formula per il calcolo della derivata di un qualsiasi ordine di una funzione complessa di variabile complessa'),
(33, 6,'Primitive','Integrale di una funzione complessa di variabile complessa'),
(34, 6,'Serie di potenze','Successioni e serie nel piano complesso'),
(35, 6,'Singolarità isolate','Sviluppi di Laurent e classificaione delle singolarità'),
(36, 6,'Teorema dei residui','Calcolo del comportamento di una funzione complessa di variabile complessa in un suo punto di singolarità'),
(37, 6,'Indicatore logaritmico','Calcolo del numero di giri compiuti da una funzione attorno allo zero');

INSERT INTO DEFINIZIONE VALUES
(1, 'Norma euclidea', 'Sia $ \vec{x} \in\mathbb{R}^{n} $, si definisce la sua norma euclidea come $ \parallel\vec{x}\parallel = \sqrt {\sum^{n}_{i=0}x^2_{i}} $.', 1, 1),
(2, 'Intorno sferico', 'Sia r > 0, $ \vec{x} \in\mathbb{R}^{n} $, definiamo il suo intorno sferico come B$_{r}\left( \vec{x}\right) = \left\{\vec{y}\in \mathbb{R}^{n}:\left\|\vec{x}-\vec{y}\right\| < r\right\}$.', 1, 1),
(3, 'Punto di accumulazione', 'Dato un insieme E$ \subseteq \mathbb{R} $, $ \vec{x} \in\mathbb{R}^{n} $ è punto di accumulazione di E se $ \forall\epsilon>0\ \exists\vec{y}\in $ E $ ,\ \vec{y}\neq\vec{x}:\ \parallel\vec{x}-\vec{y}\parallel<\epsilon $.', 1, 1),
(4, 'Punto isolato', 'Dato un insieme $ \mathbb{E} \subseteq \mathbb{R} $, $ \vec{x}\in\mathbb{E} $ è un punto isolato per $ \mathbb{E} $ se NON è un suo $\href{def(3)}{\text{punto di accumulazione}}$.', 1, 1),
(17, 'Derivata parziale', 'Sia f:X$ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R} $, v=e$ _k $=(0,0,...,0,1,0,...,0) $ \forall k=0,1,2,...,n $ versore di $ \mathbb{R}^{n} $, allora D$ _{{e}_{k}} = \frac{\partial f(\vec{x})}{\partial e_k}=f_{{e}_k}(\vec{x}) $ si dice derivata parziale di f rispetto a $ \vec{x} $.', 5, 1),
(5, 'Distanza euclidea', 'Siano $ \vec{x} $ e $ \vec{y} \in\mathbb{R}^{n} $, si definisce la distanza euclidea d($\vec{x},\vec{y}$) = $\parallel\vec{x}-\vec{y}\parallel$.', 1, 1),
(8, 'Insieme aperto', 'Un insieme E$ \subseteq\mathbb{R}^{n} $ è aperto se $ \forall\vec{x}\in $E $ \exists $U $\href{def(2)}{\text{intorno}} $ di $ \vec{x} $ vale che U$ \subseteq $E.', 1, 1),
(18, 'Gradiente', 'Sia f:X$ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R} $, $ \vec{x}\in\dot{X} $, se $ \exists\href{def(17)}{\frac{\partial f(\vec{x})}{\partial x_k}}\ \forall k=0,1,2,...,n $ f si dice derivabile in $ \vec{x} $ e definiamo il gradiente di f in $ \vec{x} $ come $ \href{def(1000)}{\triangledown} f\left(\vec{x}\right)\doteq(\frac{\partial f(\vec{x})}{\partial x_1}, \frac{\partial f(\vec{x})}{\partial x_2}, ... , \frac{\partial f(\vec{x})}{\partial x_n}) $.', 5, 1),
(19, 'Differenziabilita di una funzione scalare', 'Sia f:X $ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R} $, f è differenziabile in $ \vec{x}\in\dot{X} $ se $ \exists\vec{a}\in\mathbb{R}^{n}: $ f($ \vec{x} $) = f$ (\vec{x_0}) + \vec{a}\cdot(\vec{x}-\vec{x_0})+ $o($\parallel\vec{x}-\vec{x_0}\parallel$), per $ \vec{x}\rightarrow\vec{x_0} $.', 5, 1),
(1000, 'Nabla', 'Definiamo Nabla come un vettore in $ \mathbb{R}^{n} $ di $ \href{def(17)}{\text{derivate parziali}} $, $ \triangledown\doteq\left(\frac{\partial}{\partial x_1}, \frac{\partial}{\partial x_2}, ... , \frac{\partial}{\partial x_n}\right) $.', 5, 1),
(20, 'Piano tangente', 'Sia f:X $ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R} $, f $ \href{def(19)}{\text{differenziabile}} $ in X, sia $ \vec{x} $ =(x,y) $ \in $X, la miglior approssimazione di f in $ \vec{x} $ è g(x,y)=f(x$ _0 $, y$ _0 $)+$\href{def(17)}{\frac{\partial f( x_0 ,  y_0 )}{\partial x}}$(x-x$ _0 $)+$\frac{\partial f(x_0 , y_0 )}{\partial y}$(y-y$_0$), con graf(g) piano in $ \mathbb{R}^{3} $ passante per (x$ _0$,y$ _0 $, f(x$ _0$,y$ _0 $))$ \in\mathbb{R}^{3} $ di equazione z-$\frac{\partial f(x_0,y_0)}{\partial x}$(x-x$ _0 $)-$\frac{\partial f(x_0,y_0)}{\partial y}$(y-y$ _0$) = f(x$ _0 $,y$ _0 $).', 5, 1),
(30, 'Matrice Jacobiana', 'Sia $ \vec{x_0}\in\mathbb{R}^{n} $, la matrice Jacobiana in $ \vec{x_0} $ è M($ \vec{x_0} ) = \left(\begin{array}{c} \href{def(18)}{\triangledown f_1(\vec{x_0})}\\ \triangledown f_2(\vec{x_0})\\ ...\\ \triangledown f_m(\vec{x_0})\end{array}\right)$.', 5, 1),
(29, 'Differenziabilita di una funzione vettoriale', 'Sia $ \vec{x_0}\in\mathbb{R}^{n} $, la matrice Jacobiana in $ \vec{x_0} $Sia $ \vec{x_0}\in\mathbb{R}^{n} $, Sia $ \vec{f} $:X$ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R}^{m} $, $ \vec{f} $ è differenziabile in $ \vec{x}\in\dot{X} $ se $ \exists$M$_{m\times{n}} $ matrice : $\vec{f}$($ \vec{x} $)=$ \vec{f} (\vec{x_0}) + M\cdot(\vec{x}-\vec{x_0})+ $o($\parallel\vec{x}-\vec{x_0}\parallel$), per $ \vec{x}\rightarrow\vec{x_0} $, dove M è la $\href{def(30)}{\text{matrice Jacobiana}}$ di $ \vec{f} $.. Sia $ \vec{f} $:X$ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R}^{m} $, $ \vec{f} $ è differenziabile in $ \vec{x}\in\dot{X} $ se $ \exists$M$_{m\times{n}} $ matrice : $\vec{f}$($ \vec{x} $)=$ \vec{f} (\vec{x_0}) + M\cdot(\vec{x}-\vec{x_0})+ $o($\parallel\vec{x}-\vec{x_0}\parallel$), per $ \vec{x}\rightarrow\vec{x_0} $, dove M è la $\href{def(30)}{\text{matrice Jacobiana}}$ di $ \vec{f} $.', 9, 1),
(1001, 'Funzione limitata', 'Sia f:X$ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R} $, definiamo la funzione f limitata a U$ \subseteq $X come f$ \mid_U: $U$ \rightarrow\mathbb{R} $.', 4, 1),
(1002, 'Insieme convesso', 'A $ \subseteq\mathbb{R}^{n} $ è un insieme convesso se $ \forall\vec{x},\vec{y}\in $A, $ \left\{(1-t)\vec{x}+t\vec{y}\ :\ 0\leq t\leq1\right\}\subseteq $A.', 7 ,1),
(1003, 'Funzione convessa', 'Dato A$ \subseteq\mathbb{R}^{n} $, f:A$ \rightarrow\mathbb{R} $ si dice convessa se $ \forall\vec{x},\vec{y}\in $A : f( (1-t)$ \vec{x}-t\vec{y} $ )$\ \leq\ $(1-t)f($ \vec{x} $) + tf($ \vec{y} $) $ \forall $t$ \in(0,1)$, inoltre è strettamente connessa se vale il < nella disuguaglianza sopra.', 7, 1),
(1004, 'Funzione concava', 'Una funzione f è concava se non è $ \href{def(1003)}{\text{convessa}} $.', 7,1),
(1005, 'Punto critico', 'Sia f $ \href{def(19)}{\text{differenziabile}} $ in $ \vec{x_0}\in $Dom(f) : $ \href{def(18)}{\triangledown f(\vec{x_0})} $=0 $ \Rightarrow $ $ \vec{x_0} $ è punto critico o stazionario di f', 8, 1),
(23, 'Doppia differenziabilità', 'Si dice che f è due volte differenziabile in $ \vec{x} $ se è $ \href{def(19)}{\text{differenziabile}} $ in U $ \href{def(2)}{\text{intorno}} $ di $ \vec{x} $ e tutte le $ \href{def(17)}{\text{derivate parziali}} $ f$ _{x_1} $, f$ _{x_2} $, ... , f$ _{x_n} $ sono a loro volta differenziabili in $ \vec{x} $.', 5, 1),
(1006, 'Matrice Hessiana', 'Sia f:X$ \subseteq\mathbb{R}^2\rightarrow\mathbb{R} $, definisco la matrice Hessiana di ordine 2: $ \\ $ D$ ^{2} $f($ \vec{x} $) $ \doteq\ \begin{pmatrix}\href{def(18)}{ \triangledown f_x(\vec{x})} \\ \triangledown f_y(\vec{x}) \end{pmatrix}$ = $ \begin{pmatrix} \frac{\partial }{\partial x} \left( \frac{\partial f}{\partial x}(\vec{x})\right) & \frac{\partial }{\partial y} \left( \frac{\partial f}{\partial x}(\vec{x})\right) \\ \frac{\partial }{\partial x} \left( \frac{\partial f}{\partial y}(\vec{x})\right) & \frac{\partial }{\partial y} \left( \frac{\partial f}{\partial y}(\vec{x})\right) \end{pmatrix} $.', 5, 1),
(28, 'Forme definite e semidefinite positive e negative', 'Data una matrice simmetrica A $ _{n\times{n}} $ e la sua forma quadratica Q($ \vec{v} $) = $ \vec{v}^{\text{T}}\cdot $A$ \cdot\vec{v} $, con $ \vec{v}\in\mathbb{R}^{n} $, vale che: $ \\ $$ \textbf{1)} $ D$ ^2 $f($ \vec{x} $) definita positiva se Q($ \vec{v} $)>0, definita negativa se Q($ \vec{v} $)<0, $ \forall\vec{v}\in\mathbb{R}^{n}; $$ \\ $$ \textbf{2)} $ D$ ^2 $f($ \vec{x} $) semidefinita positiva se Q($ \vec{v} $)$ \geq $0, definita negativa se Q($ \vec{v} $)$ \leq $0, $ \forall\vec{v}\in\mathbb{R}^{n} $;$ \\ $$ \textbf{3)} $ D$ ^2 $f($ \vec{x} $) indefinita se $ \exists\vec{v_1}, \vec{v_2}\in\mathbb{R}^{n}: $ Q($ \vec{v_1} $)>0 $ \wedge $ Q($ \vec{v_2} $)<0.', 6, 1),
(14, 'Curva', 'Si dice curva una funzione continua del tipo $ \vec{\gamma} $: I$ \subseteq\mathbb{R}\rightarrow\mathbb{R}^{n} $', 3, 2),
(1007, 'Funzioni di classe $ C^1 $', 'Sia f: X$ \subseteq\mathbb{R}^{n}\rightarrow\mathbb{R} $, sia E$ \subseteq $X. Dico che f $ \in C^1( $E) se f e $ \href{def(17)}{\frac{\partial f}{\partial x}} \in C( $E)', 5,1),
(1008, 'Insieme chiuso', 'Un insieme E$ \subseteq\mathbb{R}^{n} $ è chiuso se E$ ^c $ è $ \href{def(8)}{\text{aperto}} $.', 1, 1),
(1009, 'Frontiera e chiusura di un insieme', 'Dato E$ \subseteq\mathbb{R}^{n} $, definiamo come $ \partial $ E la frontiera di E, cioè i punti di E che non sono suoi punti interni nè esterni. Inoltre la chiusura di E è $ \overline{\text{E}}\doteq\text{E}\ \cup\partial\text{E} $, che coincide con E se questo è chiuso.', 1, 1),
(52, 'Insiemi x e y-semplici', 'Un insieme E$ \subseteq\mathbb{R}^2 $ è y-semplice se $ \exists\ \text{g}_1 $(x), g$ _2 $(x)$ \in C^1 $([a,b]) tali che E={(x,y): c$ \leq $ x $ \leq $d, g$ _1 $(x)$ \leq $ y $ \leq $g$ _2 $(x)}. La stessa cosa vale, in maniera simmetrica, per gli insiemi x-semplici.', 16, 3),
(39, 'Baricentro di una curva', 'Sia $ \vec{\gamma} $: [a,b]$ \subseteq\mathbb{R}\rightarrow\mathbb{R}^3 $ una $ \href{def(14)}{\text{curva}} $, $ \mu $(x,y,z):$ \ \gamma([a,b])\rightarrow\mathbb{R} $ ($ \mu\equiv 1 $ in assenza di specifiche), M = $ \int_{\vec{\gamma}}\ \mu $(x,y,z) dxdydz, allora definiamo come baricentro il punto $ \vec{B}\in\mathbb{R}^3 $: $ \\ $ $ \vec{B}\doteq $ ($ \frac{1}{M}\int_{\vec{\gamma}} $ x$ \mu $(x,y,z) dxdydz, $ \frac{1}{M}\int_{\vec{\gamma}} $ y$ \mu $(x,y,z) dxdydz, $ \frac{1}{M}\int_{\vec{\gamma}} $ z$ \mu $(x,y,z) dxdydz).', 13, 2),
(1010, 'Equazione differenziale', 'Un''equazione differenziale di ordine m è del tipo $ F(\ t,\ y(t),\ y^{(1)},\cdot \cdot \cdot,\ y^{(m)})=0 $, nell''incognita $ y:I\subseteq\mathbb{R}\rightarrow\mathbb{R} $ e con $ A:\text{X}\subseteq\mathbb{R}^{m+2}\rightarrow\mathbb{R} $.', 23,5),
(1011, 'Equazione differenziale omogenea', 'Data un''$ \href{def(1010)}{\text{equazione differenziale}} $, per ottenere l''equazione differenziale ad essa associata va tolto il termine noto $ a(t) $.', 23, 5),
(1012, 'Numero complesso', 'Un numero $ z_0 $ è complesso, $ z_0\in\mathbb{C} $, se vale che $ z_0=\alpha+i\beta $, dove $ \alpha=Re(z_0), \beta=Im(z_0)\ \in\ \mathbb{R} $ e $ i $, detto immaginario puro, è tale che $ i^2=-1 $.', 29, 6);

INSERT INTO DERIVA VALUES
(2, 3),
(2, 4),
(3, 4),
(1, 5),
(17, 18),
(8, 18),
(8, 19),
(19, 20),
(18, 30),
(30, 29),
(1003, 1004),
(18, 1005),
(19, 1005),
(19, 23),
(2, 23),
(17, 23),
(19, 1006),
(18, 1006);

INSERT INTO TEOREMA VALUES
(1, 'proposizione', 'Disuguaglianza di Cauchy-Schwarz', 'Siano $ \vec{x},\ \vec{y}\in\mathbb{R}^{n} $','allora vale che $ \mid\vec{x}\cdot\vec{y}\mid\leq\left\|\vec{x}\right\|\cdot\left\|\vec{y}\right\| $', null, 1, 1),
(2, 'teorema', 'Disuguaglianza triangolare', 'Siano $ \vec{x} $ e $ \vec{y} \in\mathbb{R}^{n} $', 'Allora $ \parallel\vec{x}+\vec{y}\parallel\leq\parallel\vec{x}\parallel+\parallel\vec{y}\parallel $', null, 1, 1),
(18, 'teorema', 'Condizioni sufficienti di estremo locale', 'Sia f:A$ \rightarrow\mathbb{R} $, A $ \subseteq\mathbb{R}^{n}\ \href{def(8)}{\text{aperto}} $, sia $ \vec{x_0}\in $A $ \href{def(1005)}{\text{punto critico}} $ di f, U $ \href{def(2)}{\text{intorno}} $ di $ \vec{x_0} $.', 'Allora: $ \\ $$\textbf{1)}$ $ \href{def(1001)}{\text{f}\mid_U} $ (strettamente) $ \href{def(1003)}{\text{convessa}} \Rightarrow \vec{x_0} $ è punto di minimo locale (forte) di f; $ \\ $$\textbf{2)}$ f$ \mid_U $ (strettamente) $ \href{1004}{\text{concava}} \Rightarrow \vec{x_0} $ è punto di massimo locale (forte) di f. $ \\ $$ \\ $Inoltre, se f è $ \href{def(23)}{\text{2 volte differenziabile}} $ in $ \vec{x_0} $, Allora vale che: $ \\ $$\textbf{3)}$ $ \href{def(1006)}{\text{matrice Hessiana}} $ D$ ^2 $f($ \vec{x_0} $)  $ \href{def()}{\text{definita positiva}} \Rightarrow\ \vec{x_0} $ punto di minimo forte,$ \\ $$\textbf{4)}$ D$ ^2 $f($ \vec{x_0} $) definita negativa $ \Rightarrow $ $ \vec{x_0} $ è punto di massimo forte,$ \\ $$\textbf{5)}$ D$ ^2 $f($ \vec{x_0} $) indefinita $ \Rightarrow\ \vec{x_0} $ è punto di sella, $ \\ $$\textbf{6)}$ D$ ^2 $f($ \vec{x_0} $) semidefinita positiva o negativa $ \Rightarrow\ $ non si hanno abbastanza informazioni per classificare a priori la natura di $ \vec{x_0} $.', null, 8, 1),
(17, 'teorema', 'Fermat', 'Sia f:$ \mathbb{R}^{n}\rightarrow\mathbb{R} $, A $ \href{def(8)}{\text{aperto}},\ \vec{x_0} $ punto di estremo locale di A e f $ \href{def(18)}{\text{derivabile}} $ in $ \vec{x_0} $','$ \\ $ $ \Rightarrow\ \triangledown f(\vec{x_0})$ = 0.', null, 8, 1),
(25, 'teorema','Rettificabilità delle curve di classe $ C^1 $', 'Sia $ \vec{\gamma} $ è una curva di classe $ C^1 $', 'Allora $ \vec{\gamma} $ è rettificabile, inoltre la sua lunghezza si esprime con L($ \vec{\gamma} $)=$  \int_a^b \left\|\vec{\gamma}(t)\right\|dt $', null, 13, 2),
(62, 'teorema','Pappo Guldino', 'Sia A$ \subset\text{S}\subseteq\mathbb{R}^2 $ dove S è un semipiano delimitato dalla retta $ r\in\mathbb{R}^3 $', 'Allora il volume del solido generato dalla rotazione di $ \text{A} $ attorno a $ r $, cioè $ \text{R(A)} $, è $ \\ $ V$ \left( \text{R(A)}\right)=|\text{A}|_{2}\cdot L(\vec{B}_{\gamma}) $,$ \\ $ dove $ |\text{A}|_{2} $ è inteso come area di A e $ L(\vec{B}_{\gamma}) $ è la lunghezza della curva percorsa dal baricentro di $ \gamma $ nella rotazione.', null, 17, 3), 
(70, 'teorema', 'Principio di sovrapposizione', 'Consideriamo un''$ \href{def(1010)}{\text{equazione differenziale}} $.', 'Il suo integrale generale si ottiene sommando l''integrale generale dell''$ \href{def(1011)}{\text{equazione omogenea}}\ z(t) $ ad essa associata a una soluzione particolare $ \widetilde{y}(t) $. Quindi $ y(t)=z(t)+\widetilde{y}(t). $', null, 5, 1),
(74, 'teorema', 'Caratterizzazione della derivabilità in senso complesso mediante le condizioni di Cauchy-Riemann', 'Sia $ f:A\subseteq\mathbb{C}\rightarrow\mathbb{C} $ del tipo $ f\left(x+i\ y\right)=u(x,y)+i\ v(x,y) $, con $ u,v:X\subseteq\mathbb{R}^2\rightarrow\mathbb{R} $, sia $ \href{def(1012)}{\text{$\mathbb{C}\ni z_0$}} =x+i\ y $.', '$ f $ derivabile in senso complesso in $ z_0\ \Leftrightarrow\ u,v\ \href{def(19)}{\text{differenziabili}} $ in $ (x_0,y_0) $ e valgono le condizioni di Cauchy-Riemann: \begin{cases}\href{def(17)}{\text{$ \frac{\partial}{\partial x} $}} u=\frac{\partial}{\partial y} v \\\frac{\partial}{\partial y} u=-\frac{\partial}{\partial x} v\end{cases}', null, 31, 6);

INSERT INTO IPOTESI VALUES
(18,8),
(18,1003),
(18, 1004),
(18,23),
(18,28),
(17,8),
(17,18),
(25,14),
(25,1007),
(62,14),
(62,39),
(70, 1010),
(74, 1012);

INSERT INTO DIMOSTRAZIONE VALUES
(18, '1) $ f|_U $ è convessa per ipotesi, dunque $ f(\vec{x})\geq f(\vec{x_0})+\triangledown f(\vec{x_0})\cdot(\vec{x}-\vec{x_0}),\ \ \forall\vec{x}\in U $. Per il teorema di Fermat, $ \triangledown f(\vec{x_0})=0 $, Dunque $ \vec{x}\geq\vec{x_0}\ \ \forall \vec{x}\in U \Rightarrow \vec{x_0} $ è punto di minimo locale. $ \\ $3) $ D^2f(\vec{x_0}) $ è definita positiva per ipotesi. Tenendo conto che $ \triangledown f(\vec{x_0})=0 $ per Fermat, usiamo Taylor di ordine 2 con resto di Peano:$ \\ $ $ f(\vec{x})=f(\vec{x_0})+\triangledown f(\vec{x_0})\cdot(\vec{x}-\vec{x_0})+\frac{1}{2}(\vec{x}-\vec{x_0})^{T}\cdot D^2f(\vec{x_0})\cdot(\vec{x}-\vec{x_0})+o(\| \vec{x}-\vec{x_0} \|) $, per $ \vec{x}\rightarrow \vec{x_0} $. $ \\ $ $ \frac{1}{2}(\vec{x}-\vec{x_0})^{T}\cdot D^2f(\vec{x_0})\cdot(\vec{x}-\vec{x_0})\geq\frac{1}{2}\lambda_{min}\cdot\| \vec{x}-\vec{x_0} \|^2 $, dunque $ f(\vec{x})\geq f(\vec{x_0})+\frac{1}{2}\lambda_{min}\cdot\| \vec{x}-\vec{x_0} \|^2+o(\| \vec{x}-\vec{x_0} \|)\geq f(\vec{x_0})+\| \vec{x}-\vec{x_0} \|^2\cdot(\frac{\lambda_{min}}{2}+o(1))\geq f(\vec{x_0})+\frac{\lambda_{min}}{4}\cdot\| \vec{x}-\vec{x_0} \|^2,\ \vec{x}\rightarrow\vec{x_0} $ $ \\ $ $ \Rightarrow f(\vec{x})\geq f(\vec{x_0})\ \ \forall\vec{x}\neq\vec{x_0},\ \vec{x}\in X\cap B_{\delta}(\vec{x_0}), \delta>0 $ sufficientemente piccolo. $ \\ $ $ \Rightarrow\ \vec{x_0} $ è punto di minimo locale.$ \\ $6) vedi esempio.', '1) $ \Rightarrow $ 2) e 3) $ \Rightarrow $ 4) sono dimostrabili facilmente passando da f a -f. Inoltre 5) non viene fatta, in ogni caso è semplice da fare usando il resto di Peano. Perciò si dimostrano 1), 3) e 6).$ \\ $ 1) e 3) sfruttano le proprietà dello sviluppo di Taylor di ordine 2 con resto di Peano e delle funzioni convesse per dimostrare le equivalenze (anche sfruttando il teorema di Fermat), mentre la dimostrazione della 6) fa uso di alcuni esempi pratici.'),
(2, '$ \|\vec{x}+\vec{y}\|^2=(\vec{x}+\vec{y})\cdot(\vec{x}+\vec{y})=\vec{x}\cdot(\vec{x}+\vec{y})+\vec{y}\cdot(\vec{x}+\vec{y})=\vec{x}\cdot\vec{x}+\vec{x}\cdot\vec{y}+\vec{y}\cdot\vec{x}+\vec{y}\cdot\vec{y}=\vec{x}\cdot\vec{x}+\vec{y}\cdot\vec{y}+2\vec{x}\cdot\vec{y} $ $ \\ $ $ =\| \vec{x} \|^2+\| \vec{y} \|^2+2\vec{x}\cdot\vec{y}\leq(\| \vec{x}+\vec{y} \|)^2 $ $ \\ $ $ \|\vec{x}+\vec{y}\|^2\leq(\| \vec{x}+\vec{y} \|)^2\ \Rightarrow\ \|\vec{x}+\vec{y}\|^2\leq\| \vec{x}+\vec{y} \| $, che verifica la disuguaglianza triangolare.', 'usare la disuguaglianza di Cauchy-Schwarz'),
(70, 'Consideriamo un''equazione differenziale lineare del I ordine, cioè del tipo (L): $ y^{(1)}(t)=a(t)y(t)+b(t).\  y(t)=z(t)+\tilde{y}(t) $ è una soluzione di (L)? Va provata la sostituzione. $ \\ $ $ y^{(1)}(t)=z^{(1)}(t)+\tilde{y}^{(1)}(t)=a(t)z(t)+a\tilde{y}(t)+b(t)=a(t)\cdot(x(t)+\tilde{y}(t))+b(t)=a(t)y(t)+b(t) $.', 'verificare se sostituendo la formula dell''integrale generale suggerita dal PDS all''incognita dell''equazione differenziale data si ottiene una soluzione');

INSERT INTO RICHIAMA VALUES
(17, 18),
(1,2);

INSERT INTO ESEMPIO VALUES
(1, 2, 'Consideriamo i vettori $ \vec{v},\vec{u}\in\mathbb{R}^3, \vec{u}=(1,2,0), \vec{v}=(-2,0,3) $. Allora secondo la disuguaglianza triangolare dovrebbe valere che $ \|\vec{u}-\vec{v}\|\leq\|\vec{u}\|+\|\vec{v}\| $. $ \\ $ Infatti $ \|\vec{u}-\vec{v}\|=\|(1,2,0)-(-2,0,3)\|=\|(3,2,-3)\|=\sqrt{3^2+2^2+(-3)^2}=\sqrt{9+4+9}=\sqrt{22}\simeq4,69 $ $ \\ $invece $ \|\vec{u}\|=\sqrt{1^2+2^2+0^2}=\sqrt{5}\simeq2,24\ ,\ \|\vec{v}\|=\sqrt{25}=5 $. $ \\ $ $ 4,69\leq5+2,24=7,24 $.', null, 1),
(1, 62, 'Calcoliamo il volume del toro con il teorema di Pappo-Guldino. Consideriamo la rotazione attorno all''asse z dell''insieme $ A=\{(x,z):(x-R)^2+z^2\leq r^2\}=B_{r}\left((R,0)\right) $. $ \\ $$ x_{B}=R,$ la lunghezza percorsa dal baricentro $ \vec{B}=(x_{B},y_{B},z_{B}) $ è $ L(\vec{\gamma_{B}})=2\pi R $. Perciò per Pappo-Guldino: $ \\ $$ |R(A)|_3=\pi r^2\cdot 2\pi r R=2\pi^2Rr^3 $.', null, 2),
(1, 18, '$ f(x,y)=Ax^2+Bxy+Cy^2+ax+bx+c,\ \ A,B,C,a,b,c\in\mathbb{R} $. Cerco i punti critici e ne stabilisco la natura (massimo, minimo, sella). $ \triangledown f(x,y)=\begin{pmatrix}2Ax+By+a \\Bx+2Cy+b \end{pmatrix} $, devo porre $ \triangledown f(x,y)=\begin{pmatrix}0 \\ 0\end{pmatrix} $. $ \\ $$ \begin{pmatrix}2Ax+By+a \\Bx+2Cy+b \end{pmatrix}=\begin{pmatrix}0 \\ 0\end{pmatrix} $. Pongo $ M\doteq\begin{pmatrix}2A & B \\ B & 2C\end{pmatrix} $, quindi $ M\cdot\begin{pmatrix}x \\ y\end{pmatrix}=\begin{pmatrix}-a \\ -b\end{pmatrix} $.$ \\ $Esiste un unico punto critico $ \Leftrightarrow d\doteq\begin{bmatrix}2A & B \\ B & 2C\end{bmatrix}=4AC-B^2\neq 0 $. Dunque studio $ d\neq 0 $.$ \\ $Se $ A\neq 0:\ x=\frac{Bb-2aC}{d},\ y=\frac{Ba-2Ab}{d} $.$ \\ $Se $ A=0\ \wedge\ B\neq 0: $ facendo i calcoli vedo che in ogni caso (con $ d\neq 0 $) l''unico punto critico è $ \vec{x_0}=\left(\frac{Bb-2aC}{d},\ \frac{Ba-2Ab}{d} \right) $. Si osservi che $ D^2 f(x,y)=M $.$ \\ $In conclusione:$ \\ $ $ \bullet\ \vec{x_0} $ è punto di minimo locale se $ d>0\ \wedge\ (A>0\ \vee\ C>0) $,$ \\ $ $ \bullet\ \vec{x_0} $ è punto di massimo locale se $ d>0\ \wedge\ (A<0\ \vee\ C<0) $,$ \\ $ $ \bullet\ \vec{x_0} $ è punto di sella se $ d<0 $.', null, 2),
(1,70, 'Vogliamo calcolare l''integrale generale dell''equazione $ y^{(2)}(t)-4y^{(1)}(t)+4y(t)=8t^2 $, che, secondo il principio di sovrapposizione (PDS), è $ y(t)=z(t)+\tilde{y}(t) $, $ \\ $dove $ z(t) $ tale che $ z^{(2)}(t)-4z^{(1)}(t)+4z(t)=0 $ è l''equazione omogenea associata, mentre $ \tilde{y}(t) $ rappresenta una soluzione particolare di $ y(t) $.$ \\ $$ \bullet\ z^{(2)}(t)-4z^{(1)}(t)+4z(t)=0\ \Rightarrow\ \lambda^2-4\lambda+4=0,\ \lambda_1 =2,\ \lambda_2 = 2\ \\ \Rightarrow\ z(t)=Ae^{2t}+Bte^{2t},\ A,\ B\in\mathbb{R}. $ $ \\ $ $ \bullet $ $ \tilde{y}^{(2)}(t)-4\tilde{y}^{(1)}(t)+4\tilde{y}(t)=8t^2 $, cerco soluzione del tipo $ \tilde{y}(t)=Ct^2+Dt+E $. $ \\ $ $ \tilde{y}^{(1)}(t)=2Ct+D,\ \tilde{y}^{(2)}(t)=2C $. Allora $ 4Ct^2+(4D-8C)t+2C-4D+4t=8t^2 $. $ \\ $ $ \begin{cases}4C=8 \\4D-8C=0 \\ 2C-4D+4E=0\end{cases} \begin{cases}C=2 \\4D-16=0 \\ 4-4D+4E=0\end{cases} \begin{cases}C=2 \\D=4 \\ E=3\end{cases}\ \Rightarrow\ \tilde{y}=2t^2+4t+3 $. $ \\ $ Usando il PDS, $ y(t)=z(t)+\tilde{y}(t)=Ae^{2t}+Bte^{2t}+2t^2+4t+3 $ è l''integrale generale.', null, 3),
(2,18,'Vogliamo far vedere che se per $ \vec{x_0} $ punto stazionario di f vale che $ D^2f(\vec{x_0}) $ è semidefinita, allora non è possibile stabilire a priori se $ \vec{x_0} $ è punto di massimo, di minimo o di sella. Vediamo alcuni esempi pratici.$ \\ $ $ f_1 (x,y)\doteq x^4+y^4,\ \ f_2(x,y)\doteq -f_1(x,y)=-x^4-y^4,\ \ f_3(x,y)=x^4-y^4.\ $ $ \\ $ $ \triangledown f_k(x,y)=(\pm4x^3\ \pm4y^3)=0,\ k=1,2,3\ \Leftrightarrow (x,y)=\begin{pmatrix} 0 \\ 0 \end{pmatrix}.\ D^2f\begin{pmatrix} 0 \\ 0 \end{pmatrix}=\begin{pmatrix} 0 & 0 \\ 0 & 0 \end{pmatrix} $, quindi è semidefinita. $ \\ $Inoltre $ \begin{pmatrix} 0 \\ 0 \end{pmatrix} $ è:$ \\ $$ \bullet $ punto di minimo per $ f_1 $, $ \\ $ $ \bullet $ punto di massimo per $ f_2 $,$ \\ $ $ \bullet $ punto di sella per $ f_3 $.',null,2);